name: Build

# on:
#   push:
#     paths: [ '.github/workflows/build.yml','.github/workflows/buildluna.yml','src/**']
#   pull_request:
#     paths: [ '.github/workflows/build.yml','.github/workflows/buildluna.yml','src/**']

on:
  workflow_dispatch:

jobs:
  buildluna:
    uses: ./.github/workflows/buildluna.yml
    secrets: inherit