name: buildlunahook
on:
  workflow_dispatch:

jobs:
  build_xp:
    runs-on: windows-2019
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621
      - run: python src/scripts/build_lunahook.py build winxp
      - run: python src/scripts/packlunahook.py

      - uses: actions/upload-artifact@v4
        with:
          name: winxp
          path: src/cpp/LunaHook/builds
  
  # build_plugin:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       include:
  #         - bits: 32
  #           qtarch: win32_msvc2019
  #         - bits: 64
  #           qtarch: win64_msvc2019_64
  #   permissions:
  #     id-token: write
  #     attestations: write
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
  #       with:
  #         sdk-version: 22621
      
  #     - uses: jurplel/install-qt-action@v3.3.0
  #       with:
  #         version:      5.15.2
  #         host:         windows
  #         target:       desktop
  #         arch:         ${{ matrix.qtarch }}
  #         dir:          ${{ runner.temp }}
  #         setup-python: true
  #     - run: python src/scripts/build_lunahook.py plugin ${{ matrix.bits }}
  #     - run: python src/scripts/packlunahook.py

  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: plugin${{ matrix.bits }}
  #         path: src/cpp/LunaHook/builds/plugin${{ matrix.bits }}.zip
  #     - uses: softprops/action-gh-release@v2
  #       with:
  #         tag_name: LunaHook
  #         files: src/cpp/LunaHook/builds/plugin${{ matrix.bits }}.zip
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build_x:
    runs-on: windows-latest
    strategy:
      matrix:
        bits: [64]
    permissions:
      id-token: write
      attestations: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2
        with:
          sdk-version: 22621
      - run: python src/scripts/build_lunahook.py build ${{matrix.bits}}

      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.bits}}
          path: src/cpp/LunaHook/builds
  
  build:
    runs-on: windows-latest
    needs: [build_x,build_xp]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
            path: src/cpp/LunaHook/build
      - run: python src/scripts/build_lunahook.py merge
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: LunaHook
          files: src/cpp/LunaHook/builds/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}